# test30 : 1D accelerator beam
#
/run/initialize
#
/gps/particle proton

# source
/gps/pos/type Beam
/gps/direction 0 1 0

# the incident surface is in the x-z plane
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 1
#
# the beam spot is centered at the origin and is
# of 1d gaussian shape with a 3mm central plateau
/gps/pos/shape Square
/gps/pos/centre 0.0 -20.0 1000.0
/gps/pos/halfx 80.0 mm
/gps/pos/halfz 30.0 mm
/gps/pos/sigma_x 26.0 mm
/gps/pos/sigma_y 13.0 mm

# angular distribution. NB: check if considering it.
# the beam is travelling along the x-axis with 5 degrees dispersion
#/gps/ang/rot1 0 0 1
#/gps/ang/rot2 0 1 0
#/gps/ang/type beam2d
#/gps/ang/sigma_r 5. deg
#/gps/ang/sigma_x 2. deg
#/gps/ang/sigma_y 1. deg

# energy distribution
# the beam energy is in gaussian profile centered at 400 MeV
/gps/ene/type Gauss
/gps/ene/mono 2 GeV
/gps/ene/sigma 0.0156 GeV

#
# commands below are independent of gps
#

#/analysis/setFileName beamInfo
#/analysis/h1/set 1 100 200 4000 MeV
#/analysis/h2/set 1 100 -100 100 mm none linear 100 -100 100 mm none linear #x-y
#/analysis/h2/set 2 100 -100 100 mm none linear 100 -100 100 mm none linear #y-z
#/analysis/h2/set 3 100 -100 100 mm none linear 100 -100 100 mm none linear #z-x
#/analysis/h2/set 5 120 0 360 deg none linear 60 60 120 deg none linear
#
#/control/execute vis.mac

#/vis/viewer/set/viewpointThetaPhi 120. 0.
#/vis/add/trajectories smooth
#/vis/scene/add/hits

#/tracking/verbose 1
#
#/run/printProgress 100000
/run/beamOn 10
#1000000

#
