# File menu
/gui/addMenu file File
/gui/addButton file Quit exit

# Run menu
/gui/addMenu run Run
/gui/addButton run "Run 1 event" "/run/beamOn 1"
/gui/addButton run "Run 5 events" "/run/beamOn 5"
/gui/addButton run "Run 10 events" "/run/beamOn 10"
/gui/addButton run "Run 100 events" "/run/beamOn 100"

# Viewer menu
/gui/addMenu viewer Viewer
/gui/addButton viewer "Draw world" "/control/execute mac/visQt.mac"
#/gui/addButton viewer "Draw world (OI)" "/control/execute mac/visOI.mac"
/gui/addButton viewer "Set style solid" "/vis/viewer/set/style solid"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"

