# Launch protons.

# Set the detector geometry parameters.
#/essn/detector/targetRadius 100.0 cm
#/essn/detector/targetThickness 8.0 cm
#/essn/detector/worldSize  300.0 cm

/run/initialize

# Set the ntuple file name.
/analysis/ntuple/setFileName 0 essn_ntuple

# Set up the proton beam.
/gun/particle proton
/gun/energy 2 GeV
/gun/direction 0 1 0
/gun/position 0 -14 0
/tracking/verbose 2

# Run.
/run/beamOn 1000
